#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'



cookbook 'apt'
cookbook 'build-essential'
  :ref => 'v1.4.4'
cookbook 'git'
cookbook 'vim'
cookbook 'python'
